### PR TITLE
fix ISR not in IRAM bug for esp8266

### PR DESCRIPTION
**Pull request by dasdgw**

### CODE REVIEW

**Comment by dgomes** [comment]
Thank you!

**Comment by dasdgw** [comment]
Wow, that was fast.
Thank you for the lib!

**Comment by dgomes** [comment]
It was a tiny PR :)

I figured that this PR would be useful for ESP* users

**Comment by dasdgw** [comment]
Before that change my workaround was to force an older platform in platformio.ini.

platform = espressif8266@2.0.4

instead of

platform = espressif8266

Since you accepted the PR, I'll delete my fork.

**Comment by javierpagalo** [comment]
Hello, I'm using nodemcu 8266 and have the same problem, I don't know what's supposed to do with  the solution of dgomes. I'm new in this. Should I compile that?, where do I find that library?

**Comment by dasdgw** [comment]
Hi javierpagalo.

I had more issues with this lib on an esp8266 but forgot to pull-request the fixes.
Sorry about that.
At least on my setup I could fix some more ISR issues as well as #5 
You can find my forked version at https://github.com/dasdgw/homeGW

If you are using platformio you could use this lib by adding:
```
lib_deps =
	 https://github.com/dasdgw/homeGW.git
```
to your platformio.ini

@dgomes are you still mainting this lib?
If so, I'll try to create a PR by the weekend.

**Comment by dgomes** [comment]
You can open the PR :) tks

**Pull request merged**
